[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true


[dependencies]
gears = { path = "../../gears" }
anyhow = { workspace = true }

[dev-dependencies]
gears = { path = "../../gears", features = ["cli", "xmods", "governance", "utils", "mocks"] }
